name: release-typescript-action
description: Release TypeScript-based GitHub Actions

inputs:
  major-version:
    description: major version
    required: true
    default: '1'
  increment-level:
    description: minor or patch
    required: true
    default: minor
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  release-tag:
    description: If a release is created, the created release tag

runs:
  using: 'node20'
  main: 'dist/index.js'
