name: release-typescript-action
description: automate release of typescript-action

inputs:
  major-version:
    description: major version
    required: true
    default: '1'
  increment-level:
    description: semver increment level (major, minor, patch)
    required: true
    default: 'minor'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
